# Change these first
owner: yc97463 # Your GitHub organization or username, where this repository lives
repo: ndhu-uptime # The name of this repository

sites:
  - name: DHSA RPage
    url: https://dhsa.ndhu.edu.tw
    slug: dhsa-rpage
    icon: https://dhsa.ndhu.edu.tw/var/file/110/1110/msys_1110_5263550_18764.png
  - name: DHSA API (api.ndhu)
    url: https://api.dhsa.ndhu.edu.tw
    slug: dhsa-api
    icon: https://dhsa.ndhu.edu.tw/var/file/110/1110/msys_1110_5263550_18764.png
  - name: DHSA API (api.dstw)
    url: https://api.dhsa.dstw.dev
    slug: dhsa-api-dstw
    icon: https://dhsa.ndhu.edu.tw/var/file/110/1110/msys_1110_5263550_18764.png
  - name: NDHU RPage
    url: https://www.ndhu.edu.tw
    slug: ndhu-rpage
  - name: "校務系統"
    url: https://sys.ndhu.edu.tw/INC/SSO_RWD/Login.aspx
    slug: sso
  - name: "標籤"
    url: https://web.ndhu.edu.tw/academic/syslib/showname.aspx
    slug: name-tag
  - name: "選課系統"
    url: https://sys.ndhu.edu.tw/aa/class/subjselect/
    slug: course
  - name: "e 學苑"
    url: http://www.elearn.ndhu.edu.tw
    slug: elearn

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ndhu.dstw.dev
  #   baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/yc97463/ndhu-uptime
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
